Hospital_Management_System/Hospital/Hospital/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('doctor.urls')),
    path('', include('account.urls')),
    path('', include('patient.urls')),
    path('', include('restapi.urls')),
    path('admin/', admin.site.urls),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT) 

Hospital_Management_System/Hospital/doctor/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = "doctor"

urlpatterns = [
    path('', views.index, name="index"),
    path('doctor/', views.list_doc, name="list_doc"),
] 

Hospital_Management_System/Hospital/patient/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = "patient"

urlpatterns = [
    path('appointment/create/<int:pk>', views.create_appointment, name="create_appointment"),
    path('appointment/',views.list_appointment,name="list"),
    path('appointment/<int:pk>/', views.delete_appointment, name="delete_appointment"),
    path('update/<int:pk>/', views.update_appointment, name="update_appointment"), 
    path('report/upload/', views.upload_report, name="upload"),
    path('report/', views.list_report, name="rep_list"),
] 

Hospital_Management_System/Hospital/doctor/models.py
from django.db import models

# Create your models here.
class Doctor(models.Model):
    doc_id = models.IntegerField(primary_key = True)
    doc_name = models.CharField(max_length=20)
    doc_email = models.EmailField()
    specialisation = models.CharField(max_length=20)
    qualification = models.CharField(max_length=20)
    image = models.ImageField(upload_to='uploads/', null=True)

    def __str__(self):
        return self.doc_name

Hospital_Management_System/Hospital/doctor/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse
from .models import Doctor
from django.db.models import Q
from account.decorators import user_only

# Create your views here.
#decorator
@user_only
#index page
def index(request):
    return render(request=request, template_name="doctor/index.html", context={})

#listing all the doctors
def list_doc(request):
    query = " "
    context = {}
    if request.GET:
        query = request.GET['q']    
    
    
    doctor = get_data_queryset(query)
    context['doctors'] = doctor
    return render(request, "doctor/search_doctor.html", context)

#search query for doctors
def get_data_queryset(query=None):
    queryset = []
    queries = query.split(" ")
    for q in queries:
        doctors = Doctor.objects.filter(Q( doc_name__icontains=q) | Q(doc_email__icontains=q) | Q(specialisation__icontains=q))
        
        for doctor in doctors:
            queryset.append(doctor)
    
    return list(set(queryset)) 

Hospital_Management_System/Hospital/doctor/templates/doctor/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<section class="banner_part">
   <div class="container">
       <div class="row align-items-center">
           <div class="col-lg-6 col-xl-6">
               <div class="banner_text">
                   <div class="banner_text_iner">
                      
                       <h1>Bringing the future
                           of healthcare</h1>
                                 <div class="input-group">
                                         <!-- <form method="GET" class="search-bar" action="{%url 'doctor:list_doc'%}">

                                         <input type="text" class="form-control" name="q" placeholder="Search for Doctors" id="id_q">

                                         </form> -->
                                         <form method="GET" class="search-bar" action="{%url 'doctor:list_doc'%}">
                                            <div class="form-group">
                                                <div class="input-group mb-3">
                                                    <input type="text" class="form-control" name="q" id="id_q" placeholder='Search Doctors'
                                                        onfocus="this.placeholder = ''"
                                                        onblur="this.placeholder = 'Search Doctors'">
                                                    <div class="input-group-append">
                                                        <button class="btn" type="button"><i class="ti-search"></i></button>
                                                    </div>
                                                </div>
                                            </div>
                                        </form>
                                </div>
                           <div class="banner_item">
                           <div class="single_item">
                               <img src=" {% static 'img/icon/banner_1.svg' %} " alt="">
                               <h5>Emergency Cases</h5>
                           </div>
                           <div class="single_item">
                               <img src=" {% static 'img/icon/banner_2.svg' %}" alt="">
                               <h5>Easy Appointment</h5>
                           </div>
                           <div class="single_item">
                               <img src=" {% static 'img/icon/banner_3.svg' %} " alt="">
                               <h5>Qualfied Doctores</h5>
                           </div>
                       </div>
                   </div>
               </div>
           </div>
       </div>
   </div>
</section>

{% endblock %}

Hospital_Management_System/Hospital/doctor/templates/doctor/search_doctor.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<section class="doctor_part section_padding single_doctor_part">
   <div class="container">
    {% if doctors %}
       <div class="row">
         {% for d in doctors %}
           <div class="col-sm-6 col-lg-3">
               <div class="single_blog_item">
                   <div class="single_blog_img">
                       {% if d.image %}
                       <img src="{{ d.image.url}}" alt="doctor">
                       {% else %}
                       <img src= "/media/uploads/doc.jfif" alt="doctor">
                       {% endif %}
                       <div class="social_icon">
                        <a href="{% url 'patient:create_appointment' d.pk%}"><h5>Make Appointment</h5></a>
                    </div>
                   </div>
                   <div class="single_text">
                       <div class="single_blog_text">
                           <h3>{{d.doc_name}}</h3>
                           <p>{{d.specialisation}}</p>
                           <p>{{d.qualification}}</p>
                           <p>{{d.doc_email}}</p>
                       </div>
                   </div>
               </div>
           </div>
           {% endfor %}
                   </div>
                   {% else %}
                   <div class="row justify-content-center">
                     <div class="col-xl-8">
                        
                         <div class="section_tittle text-center">
                             <h2>Sorry! No Doctors found</h2>
                         </div>
                     </div>
                 </div>
                 {% endif %}
               </div>
</section>

{% endblock %}