Hospital_Management_System/Hospital/Hospital/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('doctor.urls')),
    path('', include('account.urls')),
    path('', include('patient.urls')),
    path('', include('restapi.urls')),
    path('admin/', admin.site.urls),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT) 

Hospital_Management_System/Hospital/doctor/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = "doctor"

urlpatterns = [
    path('', views.index, name="index"),
    path('doctor/', views.list_doc, name="list_doc"),
] 

Hospital_Management_System/Hospital/patient/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = "patient"

urlpatterns = [
    path('appointment/create/<int:pk>', views.create_appointment, name="create_appointment"),
    path('appointment/',views.list_appointment,name="list"),
    path('appointment/<int:pk>/', views.delete_appointment, name="delete_appointment"),
    path('update/<int:pk>/', views.update_appointment, name="update_appointment"), 
    path('report/upload/', views.upload_report, name="upload"),
    path('report/', views.list_report, name="rep_list"),
] 

Hospital_Management_System/Hospital/patient/models.py
from django.db import models
from doctor.models import Doctor 
from django.contrib.auth.models import User

# Create your models here.
class Patient(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    address = models.CharField(max_length=30)
    contact = models.IntegerField()
    doc_id = models.ManyToManyField(Doctor) 

    def __str__(self):
        return self.user.first_name

class Appointment(models.Model):
    appointment_date = models.DateField()
    appointment_time = models.TimeField()
    patient_id = models.ForeignKey(Patient, on_delete=models.CASCADE)
    doc_id = models.ForeignKey(Doctor, on_delete=models.CASCADE)
    

    def __str__(self):
        return 'Appointment Confirmed'

class Report(models.Model):
    rep_type = models.CharField(max_length=25)
    pdf = models.FileField(upload_to="report/pdfs/")
    patient_id = models.ForeignKey(Patient, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.report_id 

Hospital_Management_System/Hospital/patient/forms.py
from django import forms
from .models import Patient, Appointment, Report

#form for creating appointment 
class AppForm(forms.ModelForm):
    class Meta:
        model = Appointment
        fields = ('appointment_date', 'appointment_time')

#form for updating appointment        
class UpdateForm(forms.ModelForm):
    class Meta:
        model = Appointment
        fields = ('appointment_date', 'appointment_time')

#form for uploading reports        
class RepForm(forms.ModelForm):
    class Meta:
        model = Report
        fields = ('rep_type', 'pdf')

Hospital_Management_System/Hospital/patient/views.py
from django.shortcuts import render, redirect
from .forms import AppForm, UpdateForm, RepForm
from .models import Appointment,Patient, Report
from doctor.models import Doctor
from django.http import HttpResponse, JsonResponse
from django.contrib.auth.models import User
import json
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required
from account.decorators import user_only

# Create your views here.

#decorators
@login_required(login_url='account:patient_login')
@user_only
#create appointment
def create_appointment(request, pk=None):
    if request.method == "POST":
        form = AppForm(request.POST)
        if form.is_valid():
            p = Patient.objects.get(user_id = request.user.id)
            a = Appointment(patient_id_id = p.id)
            a.doc_id_id = pk
            a.appointment_date = form.cleaned_data['appointment_date']
            a.appointment_time = form.cleaned_data['appointment_time']
            a.save()
            return redirect('patient:list')
        
    else:
        form = AppForm()
    return render(request, "patient/appointment.html", {"form":form})

@login_required(login_url='account:patient_login')
@user_only
#listing all the created appointments
def list_appointment(request):
    p = Patient.objects.get(user_id = request.user.id)
    appointment = Appointment.objects.filter(patient_id_id = p.id)
    return render(request, "patient/list.html", {"appointments":appointment})

@login_required(login_url='account:patient_login')
@user_only
#delete appointment
def delete_appointment(request, pk=None):
    appointment = Appointment.objects.get(pk=pk)
    appointment.delete()
    return redirect('patient:list')

@login_required(login_url='account:patient_login')  
@user_only
#update appointment
def update_appointment(request, pk=None):
    if request.method == 'POST':
        form = UpdateForm(request.POST)

        if form.is_valid():
            a = Appointment.objects.get(pk=pk)
            a.appointment_date = form.cleaned_data['appointment_date']
            a.appointment_time = form.cleaned_data['appointment_time']
            a.save()
            return redirect('patient:list')

    else:
        form = UpdateForm()
        return render(request, 'patient/update_appointment.html', {'form': form})
    
    
@login_required(login_url='account:patient_login') 
@user_only
#report upload
def upload_report(request):
    if request.method == "POST":
        form = RepForm(request.POST, request.FILES)
        if form.is_valid():
            p = Patient.objects.get(user_id = request.user.id)
            r = Report(patient_id_id = p.id)
            r.rep_type = form.cleaned_data['rep_type']
            r.pdf = form.cleaned_data['pdf']
            r.save()
            return redirect('patient:rep_list')
        
    else:
        form = RepForm()
    return render(request, "patient/report.html", {"form":form})

@login_required(login_url='account:patient_login') 
@user_only
#listing all the uploaded reports
def list_report(request):
    p = Patient.objects.get(user_id = request.user.id)
    report = Report.objects.filter(patient_id_id = p.id)
    return render(request, "patient/rep_list.html", {"reports":report})

Hospital_Management_System/Hospital/patient/templates/patient/appointment.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
   <section class="our_ability section_padding">
  <section class="review_part">
      <div class="container">
          <div class="row justify-content-center">
              <div class="col-lg-10">
                  <div class="client_review_part owl-carousel">
                      <div class="client_review_single">
                          <img src="{% static 'img/Quote.png' %}" class="Quote" alt="quote">   
                  </div>
              </div>
          </div>
      </div>
      </div>
  </section>
  <section class="regervation_part padding_bottom">
   <div class="container">
       <div class="row align-items-center regervation_content">
           <div class="col-lg-7 col-md-6">
               <div class="regervation_part_iner">
                   <form method="POST" enctype="multipart/form-data">
                       <h2>Make an Appointment</h2>
                       <div>
                        {% csrf_token %}
                        {{form.as_p}}
                        
                        <button type="submit" class="regerv_btn_iner">Confirm Appointment</button>
                     
                       </div>
                   </form>
               </div>
           </div>
           <div class="col-lg-5 col-md-6">
               <div class="reservation_img">
                   <img src="{% static 'img/reservation.png' %}" alt="">
               </div>
           </div>
       </div>
   </div>
</section> 

{% endblock %}

Hospital_Management_System/Hospital/patient/templates/patient/list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<section class="our_ability section_padding">
    <section class="review_part">
        <div class="container">
            <div class="row justify-content-center">
                
                <div class="col-lg-10">
                    <div class="client_review_part owl-carousel">
                       
                        <div class="client_review_single">
                            <img src="{% static 'img/Quote.png' %}" class="Quote" alt="quote">  
                          
                    </div>
                </div>
            </div>
        </div>
        </div>
    </section>
    <section class="regervation_part padding_bottom">
     <div class="container">
         <div class="row align-items-center regervation_content">
            
                
                    <table class="table">
    
                        <thead>
                            <tr>
                                <th>Doctor Name</th>
                                <th>Appointment Date</th>
                                <th>Appointment Time</th>
                            </tr>
                        </thead>
                      
                        <tbody>
                           {% for appointment in appointments %}
                            <tr>
                                <td>{{appointment.doc_id}}</td>
                                <td>{{appointment.appointment_date}}</td>
                                <td>{{appointment.appointment_time}}</td>
                                <td>
                                <form method="POST" action="{% url 'patient:delete_appointment' appointment.pk %}">{% csrf_token %}
                                <button type="submit" class="btn btn-primary">Cancel Appointment</button>    
                                </form>
                                </td>
                                <td>
                                    <a href="{%url 'patient:update_appointment' appointment.pk %}" class="secondary-content"><button type="submit" class="btn btn-primary">Edit</button></a>
                                </td>
                                
                            </tr>        
                            {% endfor %}
                        </tbody> 
                    </table>   
                
             </div>
         </div>
     </div>
  </section> 
{% endblock %}

Hospital_Management_System/Hospital/patient/templates/patient/rep_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<section class="our_ability section_padding">
    <section class="review_part">
        <div class="container">
            <div class="row justify-content-center">
                
                <div class="col-lg-10">
                    <div class="client_review_part owl-carousel">
                       
                        <div class="client_review_single">
                            <img src="{% static 'img/Quote.png' %}" class="Quote" alt="quote">  
                          
                    </div>
                </div>
            </div>
        </div>
        </div>
    </section>

    <section class="regervation_part padding_bottom">
     <div class="container">
         <div class="row align-items-center regervation_content">

            <table class="table">
    
                <thead>
                    <tr>
                        <th>Report Type</th>
                        <th>PDF</th>
                    </tr>
                </thead>
              
                <tbody>
                   {% for report in reports %}
                    <tr>
                        <td>{{report.rep_type}}</td>
                         <td><a href="{{report.pdf.url}}">Download PDF</a></td>
                        
                    </tr>        
                    {% endfor %}
                </tbody>    
                
            </table>
             </div>
         </div>
     </div>
     <br>
     <a href="{% url 'patient:upload'%}"><button type="submit" class="btn btn-primary btn-sm" style="margin-left: 45%;">Upload Your Reports</button></a>
  </section> 
  
                        
                           

{% endblock %}

Hospital_Management_System/Hospital/patient/templates/patient/report.html
{% extends "base.html" %}

{% block content %}
<section class="feature_part single_feature_part">
   <div class="container">
       <div class="row">
           <div class="col-xl-4 col-md-4 align-self-center">
               <div class="single_feature_text ">
               </div>
           </div>
           <div class="col-lg-8 col-md-8">
               <div class="feature_item">
                   <div class="row">
                       <div class="col-lg-6 col-sm-6">
                     
                               <div class="single_feature_part">
                                 <form method="POST" enctype="multipart/form-data">
   
                                    {% csrf_token %}
                                    {{form.as_p}}
                                    
                                    <button type="submit" class="btn btn-primary btn-sm">Upload</button>
                                     
                                 </form>
                               </div>
                           </div>
                     
                   </div>
               </div>
           </div>
       </div>
   </div>
 </section>
 


{% endblock %}

Hospital_Management_System/Hospital/patient/templates/patient/update_appointment.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<section class="feature_part single_feature_part">
  <div class="container">
      <div class="row">
          <div class="col-xl-4 col-md-4 align-self-center">
              <div class="single_feature_text ">
              </div>
          </div>
          <div class="col-lg-8 col-md-8">
              <div class="feature_item">
                  <div class="row">
                      <div class="col-lg-6 col-sm-6">
                              <div class="single_feature_part">
                                <form enctype="multipart/form-data" method="POST">
                                  {% csrf_token %}
                                    {{ form.as_p }}
                                  <button type="submit" class="btn btn-primary">Update</button>
                                </form>
                              </div>
                          </div>
                  </div>
              </div>
          </div>
      </div>
  </div>
</section>

{% endblock %}