Hospital_Management_System/Hospital/Hospital/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('doctor.urls')),
    path('', include('account.urls')),
    path('', include('patient.urls')),
    path('', include('restapi.urls')),
    path('admin/', admin.site.urls),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT) 

Hospital_Management_System/Hospital/account/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = "account"

urlpatterns = [
    path('register/', views.reg_patient, name="reg_patient"),
    path('login/',views.patient_login,name="patient_login"),
    path('logged_in/',views.logged_in,name="logged_in"),
    path('logout/',views.patient_logout,name="patient_logout"),
    path('dashboard/', views.dashboard, name="dashboard"),
    path('dashboard/add_doc', views.addDoc, name="addDoc"),
    path('dashboard/update/<int:pk>', views.updateDoc, name="updateDoc"),
    path('dashboard/delete/<int:pk>', views.deleteDoc, name="deleteDoc")
] 

Hospital_Management_System/Hospital/doctor/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = "doctor"

urlpatterns = [
    path('', views.index, name="index"),
    path('doctor/', views.list_doc, name="list_doc"),
] 

Hospital_Management_System/Hospital/patient/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = "patient"

urlpatterns = [
    path('appointment/create/<int:pk>', views.create_appointment, name="create_appointment"),
    path('appointment/',views.list_appointment,name="list"),
    path('appointment/<int:pk>/', views.delete_appointment, name="delete_appointment"),
    path('update/<int:pk>/', views.update_appointment, name="update_appointment"), 
    path('report/upload/', views.upload_report, name="upload"),
    path('report/', views.list_report, name="rep_list"),
] 

Hospital_Management_System/Hospital/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Hospital Management System</title>
    <link rel="icon" href="{% static 'img/favicon.png' %}">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <!-- animate CSS -->
    <link rel="stylesheet" href="{% static 'css/animate.css' %}">
    <!-- owl carousel CSS -->
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <!-- themify CSS -->
    <link rel="stylesheet" href="{% static 'css/themify-icons.css' %}">
    <!-- flaticon CSS -->
    <link rel="stylesheet" href="{% static 'css/flaticon.css' %}">
    <!-- magnific popup CSS -->
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
    <!-- nice select CSS -->
    <link rel="stylesheet" href="{% static 'css/nice-select.css' %}">
    <!-- swiper CSS -->
    <link rel="stylesheet" href="{% static 'css/slick.css' %}">
    <!-- style CSS -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>

<body>
    <!--::header part start::-->
    <header class="main_menu home_menu">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-lg-12">
                    <nav class="navbar navbar-expand-lg navbar-light">
                        <a class="navbar-brand" href="{% url 'doctor:index' %}"> <img src=" {% static 'img/logo.png' %} " alt="logo"> </a>
                        <button class="navbar-toggler" type="button" data-toggle="collapse"
                            data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">ss
                            <span class="navbar-toggler-icon"></span>
                        </button>
                        {% if user.is_superuser %}
                        <div class="collapse navbar-collapse main-menu-item justify-content-end"
                            id="navbarSupportedContent">
                            <ul class="navbar-nav align-items-center">
                                <li class="nav-item active">
                                    <a class="nav-link" href="{%url 'account:addDoc'%}">Add Doctors</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="{%url 'account:patient_logout'%}">Logout</a>
                                </li>
                                </ul>
                        </div>

                        {% else %}
                        <div class="collapse navbar-collapse main-menu-item justify-content-end"
                            id="navbarSupportedContent">
                            <ul class="navbar-nav align-items-center">
                                <li class="nav-item active">
                                    <a class="nav-link" href="{% url 'doctor:index' %}">Home</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="/doctor/">Doctors</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'patient:list' %}">Appointments</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'patient:rep_list' %}">Reports</a>
                                </li>

                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" href="blog.html" id="navbarDropdown_1"
                                        role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        Account
                                    </a>
                                    {% if user.is_authenticated %}
                                    <div class="dropdown-menu" aria-labelledby="navbarDropdown_1">
                                        <a class="dropdown-item" href="{% url 'account:logged_in' %}">Profile</a>
                                        <a class="dropdown-item" href="{% url 'account:patient_logout' %}">Logout</a>
                                    </div>
                                    {% else %}
                                    <div class="dropdown-menu" aria-labelledby="navbarDropdown_1">
                                        <a class="dropdown-item" href="{% url 'account:patient_login' %}">Login</a>
                                        <a class="dropdown-item" href="{% url 'account:reg_patient' %}">Sign Up</a>
                                    </div>
                                    {% endif %}
                                </li>
                            </ul>
                        </div>
                        {% endif %}
                    </nav>
                </div>
            </div>
        </div>
    </header>
    <!-- Header part end-->
    {% block content %}


    {% endblock %}
    
   
    <!-- footer part start-->
  
    <!-- footer part end-->

    <!-- jquery plugins here-->

    <script src=" {% static 'js/jquery-1.12.1.min.js' %}"></script>
    <!-- popper js -->
    <script src=" {% static 'js/popper.min.js' %}"></script>
    <!-- bootstrap js -->
    <script src=" {% static 'js/bootstrap.min.js' %}"></script>
    <!-- easing js -->
    <script src=" {% static 'js/jquery.magnific-popup.js' %}"></script>
    <!-- swiper js -->
    <script src=" {% static 'js/swiper.min.js' %}"></script>
    <!-- swiper js -->
    <script src=" {% static 'js/masonry.pkgd.js' %} "></script>
    <!-- particle {% static '' %} s js -->
    <script src=" {% static ' js/owl.carousel.min.js' %}"></script>
    <script src=" {% static 'js/jquery.nice-select.min.js' %} "></script>
    <!-- swiper j {% static '' %} s -->
    <script src=" {% static 'js/slick.min.js' %} "></script>
    <script src=" {% static 'js/jquery.counterup.min.js' %} "></script>
    <script src=" {% static 'js/waypoints.min.js' %} "></script>
    <!-- contact  {% static '' %} js -->
    <script src=" {% static 'js/jquery.ajaxchimp.min.js' %} "></script>
    <script src=" {% static 'js/jquery.form.js' %} "></script>
    <script src=" {% static 'js/jquery.validate.min.js' %} "></script>
    <script src=" {% static 'js/mail-script.js' %} "></script>
    <script src=" {% static 'js/contact.js' %} "></script>
    <!-- custom js -->
    <script src=" {% static 'js/custom.js' %} "></script>
</body>

</html>